### ISSUE TITLE
LRPs missing vs. running

### ISSUE THREAD

**Issue by felixfriedrich** [cloudfoundry/docs-loggregator#25]
In https://github.com/cloudfoundry/docs-loggregator/blob/master/all_metrics.html.md.erb there is a description of LRPsMissing, which is `Total number of Tasks running on cells. Emitted every 30 seconds`. While LRPsRunning is mentioning instances not tasks, LRPsMissing is also using the word `running` instead of `missing`.

I would appreciate a clarification here :-)

Thanks,

Felix

**Comment by jncd** [comment]
Thanks @felixfriedrich 
I've cross-references with the original source and made the fix for the LRPsMissing metric description. (It might take a few days before you see the change in production. The correction is "LRPsMissing: Total number of LRP instances that are desired but have no record in the BBS.")
